name: 開発タスク
description: Factrailの機能追加・バグ修正・改善タスク
labels: ["claude:auto"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 このテンプレートについて

        このissueを作成すると、Claudeが自動で以下を行います：
        1. 要件の確認と方針の提案
        2. タスクリストの作成
        3. あなたがタスクリストを承認し、Claudeにassignすると実装を開始
        4. 実装完了後、PRを作成

  - type: dropdown
    id: type
    attributes:
      label: タスクの種類
      options:
        - 機能追加
        - バグ修正
        - リファクタリング
        - ドキュメント
        - その他
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 実現したいこと / 問題の内容
      description: 何を実現したいですか？バグの場合は、何が起きていて何が期待される動作ですか？
      placeholder: |
        例：
        - GitHubのPRイベントをFactとして記録したい
        - Slack投稿時にエラーが発生する（期待：正常に投稿される）
    validations:
      required: true

  - type: dropdown
    id: target_app
    attributes:
      label: 対象アプリ
      options:
        - API (NestJS)
        - Web (Next.js)
        - 両方
        - その他/不明
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: 関連ドメイン
      description: 該当するものを選択してください
      options:
        - Facts（ログの管理）
        - Integrations（外部連携管理）
        - Settings（設定管理）
        - GitHub連携
        - Slack連携
        - F2A連携
        - Webhooks
        - 認証/セキュリティ
        - UI/UX
        - インフラ/デプロイ
        - その他

  - type: textarea
    id: context
    attributes:
      label: 背景・補足情報
      description: なぜこの機能が必要ですか？関連するIssueやドキュメントがあればリンクを貼ってください
      placeholder: |
        背景：
        関連Issue：
        参考資料：
    validations:
      required: false

  - type: textarea
    id: files
    attributes:
      label: 関連ファイル（わかれば）
      placeholder: |
        例：
        - apps/api/src/facts/facts.controller.ts
        - apps/web/app/setup/page.tsx
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 完了条件
      description: このタスクが完了したと言える条件は何ですか？
      placeholder: |
        - [ ]
        - [ ]
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        **次のステップ：**
        1. このissueを作成します
        2. Issue作成後、以下のコメントを投稿してClaudeを起動してください：
           ```
           @claude このissueの内容を確認し、以下を日本語で提案してください：
           1. 実装方針の提案（技術的アプローチ、影響範囲、考慮点）
           2. 詳細タスクリスト（実装ステップ、各ステップの説明）
           3. 確認事項（不明点や質問があれば）
           ```
        3. 提案内容を確認し、必要に応じて対話で調整してください
        4. タスクリストに問題がなければ、Claudeをassignしてください
        5. Claudeが実装を開始し、完了後にPRを作成します
