name: 機能リクエスト / バグ報告
description: Factrailへの機能追加やバグ修正の依頼
labels: ["claude:pending"]
body:
  # 基本情報（必須）
  - type: dropdown
    id: type
    attributes:
      label: 種類
      options:
        - 機能追加
        - バグ修正
        - リファクタリング
        - ドキュメント
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 実現したいこと / 問題の内容
      placeholder: |
        何を実現したいですか？
        バグの場合：何が起きていて、何が期待される動作ですか？
    validations:
      required: true

  # 対象の特定
  - type: dropdown
    id: target_app
    attributes:
      label: 対象アプリ
      options:
        - API (NestJS)
        - Web (Next.js)
        - 両方
        - その他/不明
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: 関連ドメイン
      description: 該当するものを選択
      options:
        - Facts（ログの管理）
        - Integrations（外部連携管理）
        - GitHub連携
        - Slack連携
        - F2A連携
        - 認証/セキュリティ
        - UI/UX
        - インフラ/デプロイ
        - その他

  # 任意の補足
  - type: textarea
    id: context
    attributes:
      label: 背景・補足情報
      placeholder: |
        なぜこの機能が必要ですか？
        関連するIssueやドキュメントがあればリンクを貼ってください
    validations:
      required: false

  - type: textarea
    id: files
    attributes:
      label: 関連ファイル（わかれば）
      placeholder: |
        例：
        - apps/api/src/facts/facts.controller.ts
        - apps/web/app/facts/page.tsx
    validations:
      required: false
