name: 開発タスク
description: 開発用テンプレート（合意形成 → 実装）
labels: ["task"]
body:
  # ========================================
  # 運用ルール（説明文として表示）
  # ========================================
  - type: markdown
    attributes:
      value: |
        ### 📋 テンプレート運用ルール
        - 🔶 必須項目 / 🔷 非必須項目
        - 合意形成は「タスクの目的・スコープ・影響範囲」の認識を揃える場とする
        - 作業中にスコープ外の不具合が見つかった場合、**修正可否は必ず他者に確認すること**

  # ========================================
  # 🔶 タスクの目的・背景
  # ========================================
  - type: textarea
    id: purpose
    attributes:
      label: 🔶 タスクの目的・背景
      description: なぜこの対応が必要か、何を解決したいか
      placeholder: |
        合意形成・確認を行って記載する
    validations:
      required: true

  # ========================================
  # 🔶 範囲（スコープ）の確認
  # ========================================
  - type: markdown
    attributes:
      value: |
        ---
        ### 🔶 範囲（スコープ）の確認
        今回「やること / やらないこと」を明確にする

  - type: dropdown
    id: scope_web
    attributes:
      label: "WEB - 変更有無"
      options:
        - 変更なし
        - 変更あり
        - 要確認
    validations:
      required: true

  - type: textarea
    id: scope_web_detail
    attributes:
      label: "WEB - 作業内容"
      placeholder: 変更ありの場合は内容を記載
    validations:
      required: false

  - type: dropdown
    id: scope_bff
    attributes:
      label: "BFF - 変更有無"
      options:
        - 変更なし
        - 変更あり
        - 要確認
    validations:
      required: true

  - type: textarea
    id: scope_bff_detail
    attributes:
      label: "BFF - 作業内容"
      placeholder: 変更ありの場合は内容を記載
    validations:
      required: false

  - type: dropdown
    id: scope_service
    attributes:
      label: "SERVICE - 変更有無"
      options:
        - 変更なし
        - 変更あり
        - 要確認
    validations:
      required: true

  - type: textarea
    id: scope_service_detail
    attributes:
      label: "SERVICE - 作業内容"
      placeholder: 変更ありの場合は内容を記載
    validations:
      required: false

  # ========================================
  # 🔶 前提条件
  # ========================================
  - type: markdown
    attributes:
      value: |
        ---
        ### 🔶 前提条件

  - type: input
    id: deadline
    attributes:
      label: 期日
      placeholder: "例: 2025/02/15"
    validations:
      required: true

  - type: dropdown
    id: has_constraints
    attributes:
      label: 制約（仕様書・参考資料・ルール等）
      options:
        - なし
        - あり
    validations:
      required: true

  - type: textarea
    id: constraints_detail
    attributes:
      label: 制約の内容
      placeholder: ありの場合は内容を記載（リンク等）
    validations:
      required: false

  # ========================================
  # 🔶 完了条件・確認項目
  # ========================================
  - type: textarea
    id: done_definition
    attributes:
      label: 🔶 完了条件
      description: このIssueが終わったと言える状態
      placeholder: |
        - 
        -
    validations:
      required: true

  - type: textarea
    id: check_items
    attributes:
      label: 🔶 確認項目
      placeholder: |
        - 
        -
    validations:
      required: true

  # ========================================
  # 🔶 既存コードへの影響
  # ========================================
  - type: markdown
    attributes:
      value: |
        ---
        ### 🔶 既存コードへの影響
        既存実装に対する影響有無をレイヤー単位で記載（技術的な詳細説明は不要）

  - type: dropdown
    id: impact_web
    attributes:
      label: "WEB への影響"
      options:
        - 変更なし
        - 変更あり
        - 要確認
    validations:
      required: true

  - type: input
    id: impact_web_detail
    attributes:
      label: "WEB 影響の概要"
      placeholder: 変更あり・要確認の場合は簡単に記載
    validations:
      required: false

  - type: dropdown
    id: impact_bff
    attributes:
      label: "BFF への影響"
      options:
        - 変更なし
        - 変更あり
        - 要確認
    validations:
      required: true

  - type: input
    id: impact_bff_detail
    attributes:
      label: "BFF 影響の概要"
      placeholder: 変更あり・要確認の場合は簡単に記載
    validations:
      required: false

  - type: dropdown
    id: impact_service
    attributes:
      label: "SERVICE への影響"
      options:
        - 変更なし
        - 変更あり
        - 要確認
    validations:
      required: true

  - type: input
    id: impact_service_detail
    attributes:
      label: "SERVICE 影響の概要"
      placeholder: 変更あり・要確認の場合は簡単に記載
    validations:
      required: false

  - type: dropdown
    id: impact_other
    attributes:
      label: "その他（DB / 外部API / バッチ等）への影響"
      options:
        - 変更なし
        - 変更あり
        - 要確認
    validations:
      required: true

  - type: input
    id: impact_other_detail
    attributes:
      label: "その他 影響の概要"
      placeholder: 変更あり・要確認の場合は簡単に記載
    validations:
      required: false

  # ========================================
  # 🔷 調査事項（非必須）
  # ========================================
  - type: textarea
    id: investigation
    attributes:
      label: 🔷 調査事項（非必須）
      description: 事前に調査が必要な内容や、調査した結果
      placeholder: |
        調査内容：
        調査結果：
    validations:
      required: false

  # ========================================
  # 🔶 作業フローの確認
  # ========================================
  - type: markdown
    attributes:
      value: |
        ---
        ### 🔶 作業フローの確認（大まかな流れ）

  - type: dropdown
    id: has_figma
    attributes:
      label: Figma資料
      options:
        - なし
        - あり
    validations:
      required: true

  - type: input
    id: figma_url
    attributes:
      label: Figma URL
      placeholder: "https://www.figma.com/..."
    validations:
      required: false

  - type: textarea
    id: workflow
    attributes:
      label: 実作業フロー（概要）
      description: 詳細なタスクリストではなく、作業の全体像
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true

  # ========================================
  # 🔶 リスク / 不明点
  # ========================================
  - type: textarea
    id: risks
    attributes:
      label: 🔶 リスク / 不明点
      description: 作業前に認識しているリスク・判断が必要な点
      placeholder: |
        -
    validations:
      required: true

  # ========================================
  # 合意形成後の注記
  # ========================================
  - type: markdown
    attributes:
      value: |
        ---
        > ⚠️ **ここまで記載したらissueの確認・合意形成を行う**
        > 
        > 詳細タスクリストは合意形成後にコメントで追記してください。
        > 
        > ※作業中にスコープ内か判断のつかない不具合が発生した際は、修正がスコープ内かどうかを必ず他者と確認すること。
